// Print the sizes of each variable
# include <iostream>
using namespace std;
int main(){
	cout<<"int ="<<"\t"<<sizeof(int)<<"\n";
	cout<<"short ="<<"\t"<<sizeof(short)<<"\n";
	cout<<"long ="<<"\t"<<sizeof(long)<<"\n";
	cout<<"char ="<<"\t"<<sizeof(char)<<"\n";
	cout<<"float ="<<"\t"<<sizeof(float)<<"\n";
	cout<<"double ="<<"\t"<<sizeof(double)<<"\n";
	cout<<"bool ="<<"\t"<<sizeof(bool)<<"\n";	
}
